# Book settings
title                       : "fINALrEPORT"
author                      : "ShihRanLin"
copyright                   : "2025"
logo                        : 

# Execution settings
execute:  
  execute_notebooks         : off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")